import type {Metadata} from "next"
import {Redressed, Noto_Sans_Myanmar} from "next/font/google"
import "./globals.css"
import Layout from "@/components/Layout"
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import Title from "@/components/Title"

const mincho = Redressed({weight: "400", subsets: ["latin"]})
export const mmFont = Noto_Sans_Myanmar({weight: "400", subsets: ["myanmar"]})

export const metadata: Metadata = {
    title: "Pick A Pile",
    description: "Generated by create next app",
}

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="shortcut icon"
                    href="/favicon.png"
                    type="image/png"
                />
            </head>
            <body className={`${mincho.className} bg-custom-color text-white`}>
                <Header />
                <Title />
                <Layout>{children}</Layout>
                <Footer />
            </body>
        </html>
    )
}
